# Pre-commit hooks for code quality and security
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-executables-have-shebangs
      - id: check-case-conflict
      - id: check-docstring-first
      - id: detect-private-key
      - id: check-added-large-files
        args: ['--maxkb=1000']

  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        language_version: python3.11
        args: ['--config', 'pyproject.toml']

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.0
    hooks:
      - id: ruff
        args: ['--fix', '--exit-non-zero-on-fix']

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.0
    hooks:
      - id: mypy
        additional_dependencies:
          - pydantic>=2.5.0
          - boto3-stubs[essential]
          - types-requests
          - types-redis
        args: ['--config-file', 'pyproject.toml']

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: ['-c', 'pyproject.toml']
        additional_dependencies: ['bandit[toml]']

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']

  - repo: https://github.com/gitguardian/ggshield
    rev: v1.25.0
    hooks:
      - id: ggshield
        language: python
        stages: [commit]

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.0
    hooks:
      - id: gitleaks

  - repo: local
    hooks:
      - id: pytest-fast
        name: pytest-fast
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
        args: ['-x', '--tb=short', '-m', 'not slow and not integration']

      - id: safety-check
        name: safety-check
        entry: safety
        language: system
        args: ['check', '--json']
        pass_filenames: false
        always_run: true

      - id: flutter-analyze
        name: flutter-analyze
        entry: bash
        language: system
        args: ['-c', 'cd mobile_app && flutter analyze']
        files: '^mobile_app/.*\.dart$'
        pass_filenames: false

      - id: flutter-format
        name: flutter-format
        entry: bash
        language: system
        args: ['-c', 'cd mobile_app && dart format --set-exit-if-changed .']
        files: '^mobile_app/.*\.dart$'
        pass_filenames: false

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.83.5
    hooks:
      - id: terraform_fmt
        args: ['--args=-recursive']
      - id: terraform_validate
      - id: terraform_tflint
        args: ['--args=--only=terraform_deprecated_interpolation',
               '--args=--only=terraform_deprecated_index',
               '--args=--only=terraform_unused_declarations',
               '--args=--only=terraform_comment_syntax',
               '--args=--only=terraform_documented_outputs',
               '--args=--only=terraform_documented_variables',
               '--args=--only=terraform_typed_variables',
               '--args=--only=terraform_module_pinned_source',
               '--args=--only=terraform_naming_convention',
               '--args=--only=terraform_required_version',
               '--args=--only=terraform_required_providers',
               '--args=--only=terraform_standard_module_structure',
               '--args=--only=terraform_workspace_remote']
