name: petty
description: Petty mobile app (Flutter) with glassmorphism UI
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.2
  go_router: ^6.0.2
  http: ^0.13.5
  sentry_flutter: ^7.14.0
  shared_preferences: ^2.2.2
  dynamic_color: ^1.6.8
  package_info_plus: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/backgrounds/
